// <auto-generated />
using System;
using AirWatch.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace AirWatch.Infrastructure.Migrations
{
    [DbContext(typeof(AirWatchContext))]
    partial class AirWatchContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirWatch.Domain.Entities.AirReading", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_reading");

                    b.Property<int?>("Aqi")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("aqi");

                    b.Property<string>("Category")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("category");

                    b.Property<Guid>("CityId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_city");

                    b.Property<decimal?>("Co")
                        .HasColumnType("decimal(8,3)")
                        .HasColumnName("co");

                    b.Property<decimal?>("Co2")
                        .HasColumnType("decimal(8,3)")
                        .HasColumnName("co2");

                    b.Property<decimal?>("Humidity")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("humidity");

                    b.Property<decimal?>("No2")
                        .HasColumnType("decimal(8,3)")
                        .HasColumnName("no2");

                    b.Property<decimal?>("O3")
                        .HasColumnType("decimal(8,3)")
                        .HasColumnName("o3");

                    b.Property<decimal?>("Pm10")
                        .HasColumnType("decimal(8,3)")
                        .HasColumnName("pm10");

                    b.Property<decimal?>("Pm25")
                        .HasColumnType("decimal(8,3)")
                        .HasColumnName("pm25");

                    b.Property<DateTime>("ReadingAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("reading_at");

                    b.Property<Guid?>("SensorId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_sensor");

                    b.Property<decimal?>("So2")
                        .HasColumnType("decimal(8,3)")
                        .HasColumnName("so2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("source");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("temperature");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("idx_air_reading_category");

                    b.HasIndex("ReadingAt")
                        .HasDatabaseName("idx_air_reading_date");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("idx_air_reading_sensor");

                    b.HasIndex("CityId", "ReadingAt")
                        .HasDatabaseName("idx_air_reading_city_date");

                    b.ToTable("AIR_READING", (string)null);
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.AlertConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_alert_config");

                    b.Property<Guid>("CityId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("CHAR(2)")
                        .HasColumnName("operator");

                    b.Property<string>("Pollutant")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("pollutant");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("severity");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("decimal(8,3)")
                        .HasColumnName("threshold");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_user");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("idx_alert_config_city");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_alert_config_user");

                    b.HasIndex("UserId", "CityId", "Pollutant", "Operator")
                        .IsUnique()
                        .HasDatabaseName("uq_alert_config");

                    b.ToTable("ALERT_CONFIG", (string)null);
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.AlertEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_event");

                    b.Property<Guid>("AlertConfigId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_alert_config");

                    b.Property<DateTime>("EventAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("event_at");

                    b.Property<decimal>("MeasuredValue")
                        .HasColumnType("decimal(8,3)")
                        .HasColumnName("measured_value");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("message");

                    b.Property<string>("NotificationSent")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("notification_sent");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("notified_at");

                    b.Property<Guid>("ReadingId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_reading");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AlertConfigId")
                        .HasDatabaseName("idx_alert_event_config");

                    b.HasIndex("EventAt")
                        .HasDatabaseName("idx_alert_event_date");

                    b.HasIndex("ReadingId")
                        .HasDatabaseName("idx_alert_event_reading");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_alert_event_status");

                    b.ToTable("ALERT_EVENT", (string)null);
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_city");

                    b.Property<decimal?>("AltitudeM")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("altitude_m");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("name");

                    b.Property<long?>("Population")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("population");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("state");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("idx_city_country");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("idx_city_lat_lng");

                    b.ToTable("CITY", (string)null);
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_country");

                    b.Property<string>("Continent")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("continent");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasColumnType("CHAR(2)")
                        .HasColumnName("iso_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("IsoCode")
                        .IsUnique()
                        .HasDatabaseName("uq_country_iso");

                    b.ToTable("COUNTRY", (string)null);
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.IntegrationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_log");

                    b.Property<string>("ApiName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("api_name");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_city");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("endpoint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("error_message");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("CHAR(6)")
                        .HasColumnName("http_method");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("http_status");

                    b.Property<int?>("RecordsCount")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("records_count");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("requested_at");

                    b.Property<int?>("ResponseMs")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("response_ms");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("result");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("idx_integration_log_city");

                    b.HasIndex("Result")
                        .HasDatabaseName("idx_integration_log_result");

                    b.HasIndex("ApiName", "RequestedAt")
                        .HasDatabaseName("idx_integration_log_api");

                    b.ToTable("INTEGRATION_LOG", (string)null);
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_sensor");

                    b.Property<Guid>("CityId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_city");

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("installed_at");

                    b.Property<DateTime?>("LastReadingAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("last_reading_at");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,6)")
                        .HasColumnName("latitude");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("location");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("idx_sensor_city");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_sensor_status");

                    b.ToTable("SENSOR", (string)null);
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_user");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("email");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("name");

                    b.Property<string>("NotifyEmail")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("notify_email");

                    b.Property<string>("NotifyPush")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("notify_push");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("idx_users_city");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_users_email");

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.AirReading", b =>
                {
                    b.HasOne("AirWatch.Domain.Entities.City", "City")
                        .WithMany("AirReadings")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_air_reading_city");

                    b.HasOne("AirWatch.Domain.Entities.Sensor", "Sensor")
                        .WithMany("AirReadings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_air_reading_sensor");

                    b.Navigation("City");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.AlertConfig", b =>
                {
                    b.HasOne("AirWatch.Domain.Entities.City", "City")
                        .WithMany("AlertConfigs")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alert_config_city");

                    b.HasOne("AirWatch.Domain.Entities.User", "User")
                        .WithMany("AlertConfigs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alert_config_user");

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.AlertEvent", b =>
                {
                    b.HasOne("AirWatch.Domain.Entities.AlertConfig", "AlertConfig")
                        .WithMany("AlertEvents")
                        .HasForeignKey("AlertConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alert_event_config");

                    b.HasOne("AirWatch.Domain.Entities.AirReading", "AirReading")
                        .WithMany("AlertEvents")
                        .HasForeignKey("ReadingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alert_event_reading");

                    b.Navigation("AirReading");

                    b.Navigation("AlertConfig");
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.City", b =>
                {
                    b.HasOne("AirWatch.Domain.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_city_country");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.IntegrationLog", b =>
                {
                    b.HasOne("AirWatch.Domain.Entities.City", "City")
                        .WithMany("IntegrationLogs")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_integration_log_city");

                    b.Navigation("City");
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.Sensor", b =>
                {
                    b.HasOne("AirWatch.Domain.Entities.City", "City")
                        .WithMany("Sensors")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_city");

                    b.Navigation("City");
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.User", b =>
                {
                    b.HasOne("AirWatch.Domain.Entities.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_city");

                    b.Navigation("City");
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.AirReading", b =>
                {
                    b.Navigation("AlertEvents");
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.AlertConfig", b =>
                {
                    b.Navigation("AlertEvents");
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.City", b =>
                {
                    b.Navigation("AirReadings");

                    b.Navigation("AlertConfigs");

                    b.Navigation("IntegrationLogs");

                    b.Navigation("Sensors");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.Sensor", b =>
                {
                    b.Navigation("AirReadings");
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.User", b =>
                {
                    b.Navigation("AlertConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
